apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-backstage
  annotations:
    github.com/project-slug: jpepiot/demo-backstage
spec:
  type: other
  lifecycle: unknown
  owner: guests
