apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dmp-services-entity
  title: Entity service
  description: Manages activity, item and file informations
  annotations:
    backstage.io/techdocs-ref: dir:.
    sonarqube.org/project-key: dmp-services-entity
    gitlab.com/project-id: '702'
    gitlab.com/instance: frbor-gitlab01.emea.thermo.com
    backstage.io/kubernetes-id: <BACKSTAGE_ENTITY_NAME>
    backstage.io/kubernetes-namespace: master
  tags:
    - dotnetcore
  links:
    - url: https://frbor-gitlab01.emea.thermo.com/DMP/dmp-services/dmp-services-entity
      title: GitLab repo
      icon: gitlab
spec:
  type: service
  lifecycle: production
  owner: core-team
  dependsOn:
    - resource:default/dmp-databases-entity
  providesApis:
    - entity-api
  consumesApis:
    - storage-api
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dmp-databases-entity
  description: Stores entity details
  tags:
    - postgresql
spec:
  type: database
  owner: core-team
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: entity-api
  description: Manages activity, item and file informations API interfaces
  title: Entity Rest API
spec:
  type: openapi
  lifecycle: production
  owner: core-team
  definition:
    $text: http://registry-athena-tools.frbor-seti-lb.emea.thermo.com/apis/registry/v2/groups/athena-private/artifacts/entity-api
