apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dmp-services-storage
  title: Storage service
  description: Manages file storage
  annotations:
    sonarqube.org/project-key: dmp-services-storage
    gitlab.com/project-id: '472'
    gitlab.com/instance: frbor-gitlab01.emea.thermo.com
  tags:
    - dotnetcore
spec:
  type: service
  lifecycle: production
  owner: core-team
  system: file-management
  dependsOn:
    - resource:default/dmp-databases-entity
  providesApis:
    - storage-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: storage-api
  description: Manages file storage API interface
  title: Storage Rest API
spec:
  type: openapi
  lifecycle: production
  owner: core-team
  definition: 
    $text: http://registry-athena-tools.frbor-seti-lb.emea.thermo.com/apis/registry/v2/groups/athena-public/artifacts/public-api
