apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dmp-components-kafka
  title: Kafka component
  description: Kafka platform
spec:
  type: messaging
  owner: system-team
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kafka-rest
  title: Kafka Rest proxy
  description: Kafka Rest Proxy
spec:
  type: service
  lifecycle: production
  owner: system-team
  subcomponentOf: dmp-components-kafka
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kafka-connect
  title: Kafka connect
  description: Kafka connect
spec:
  type: service
  lifecycle: production
  owner: system-team
  subcomponentOf: dmp-components-kafka
