apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dmp-services-storage
  title: Storage service
  description: Manages file storage
  tags:
    - dotnetcore
spec:
  type: service
  lifecycle: production
  owner: core-team
  dependsOn:
    - resource:default/dmp-databases-entity
  providesApis:
    - storage-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: storage-api
  description: Manages file storage API interface
  title: Storage Rest API
spec:
  type: openapi
  lifecycle: production
  owner: core-team
  definition: |
    openapi: 3.0.1
    info:
        title: Storage service API
        version: 0.0.0-1.22
        description: Storage service Open API Specifications
