apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dmp-services-aggregator
  title: API Gateway service
  description: API Gateway service
spec:
  type: service
  lifecycle: production
  owner: core-team
  consumesApis:
    - entity-api
    - user-api
  providesApis:
    - public-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: public-api
  description: Athena Public API
  title: Athena Public API
spec:
  type: openapi
  lifecycle: production
  owner: core-team
  definition:
    $text: blob:http://registry-athena-tools.frbor-seti-lb.emea.thermo.com/f4cf9115-f389-49d2-9161-76341679a385
