apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dmp-components-keycloak
  title: Identity provider
  description: Identity provider
spec:
  type: service
  lifecycle: production
  owner: system-team
  providesApis:
    - keycloak-admin-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: keycloak-admin-api
  description: Manages User & Role API interfaces
  title: Keycloak Rest API
spec:
  type: openapi
  lifecycle: production
  owner: system-team
  definition: |
    openapi: 3.0.1
    info:
        title: Keycloak API
        version: 0.0.0-1.22
        description: Keycloak Admin Open API Specifications
