apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dmp-services-aggregator
  title: API Gateway service
  description: API Gateway service
  tags:
    - dotnetcore
spec:
  type: service
  lifecycle: production
  owner: core-team
  consumesApis:
    - entity-api
    - user-api
  providesApis:
    - public-api
  tags:
    - api
    - rest
    - dotnetcore
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: public-api
  description: Athena Public API
  title: Athena Public API
spec:
  type: openapi
  lifecycle: production
  owner: core-team
  definition: 
    $text: http://registry-athena-tools.frbor-seti-lb.emea.thermo.com/apis/registry/v2/groups/athena-public/artifacts/public-api
